#ifndef __CONFIG_DEVICE_H__
#define __CONFIG_DEVICE_H__

// #define DEVICE_FZ_DM4_TEAROOM_AC_GREE
// #define DEVICE_CL_DJROOM_AC_MCQUAY
// #define DEVICE_CL_CXY_SPEAKER_SANSUI_P300

// ESP32_WROOM 采集器
#define DEVICE_TEST_SNIFFER_ESP32_WROOM

#endif